#!/usr/bin/bash
curl -o /usr/bin/menu -Ls https://raw.githubusercontent.com/Shadowdragon1997/script-menu/main/menu.sh
chmod +x /usr/bin/menu
ln -s /usr/bin/menu /usr/bin/menu # Chữ thường tương thích
chmod +x /usr/bin/menu
